-- MySQL Script generated by MySQL Workbench
-- Sat Dec  1 19:33:31 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_loja
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_loja
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_loja` DEFAULT CHARACTER SET utf8 ;
USE `db_loja` ;

-- -----------------------------------------------------
-- Table `db_loja`.`tb_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_loja`.`tb_status` (
  `id_status` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NULL,
  `description` VARCHAR(500) NULL,
  PRIMARY KEY (`id_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_loja`.`tb_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_loja`.`tb_address` (
  `id_address` INT NOT NULL,
  `id_user` INT NOT NULL,
  `CEP` INT NOT NULL,
  `street` VARCHAR(128) NULL,
  `number` INT NULL,
  `block` INT NULL,
  `sector` VARCHAR(128) NULL,
  `city` VARCHAR(128) NULL,
  `state` VARCHAR(60) NULL,
  `status` INT NULL,
  PRIMARY KEY (`id_address`),
  INDEX `fk_address_status_idx` (`status` ASC) VISIBLE,
  CONSTRAINT `fk_address_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `db_loja`.`tb_user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_address_status`
    FOREIGN KEY (`status`)
    REFERENCES `db_loja`.`tb_status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_loja`.`tb_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_loja`.`tb_user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `id_address` INT NULL,
  `name` VARCHAR(128) NULL,
  `login` VARCHAR(128) NULL,
  `email` VARCHAR(128) NULL,
  `phone` INT NULL,
  `status` INT NULL,
  PRIMARY KEY (`id_user`),
  INDEX `fk_user_status_idx` (`status` ASC) VISIBLE,
  INDEX `fk_user_adress_idx` (`id_address` ASC) VISIBLE,
  CONSTRAINT `fk_user_status`
    FOREIGN KEY (`status`)
    REFERENCES `db_loja`.`tb_status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_adress`
    FOREIGN KEY (`id_address`)
    REFERENCES `db_loja`.`tb_address` (`id_address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_loja`.`tb_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_loja`.`tb_type` (
  `id_type` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NULL,
  `description` VARCHAR(1000) NULL,
  `status` INT NULL,
  PRIMARY KEY (`id_type`),
  INDEX `fk_type_status_idx` (`status` ASC) VISIBLE,
  CONSTRAINT `fk_type_status`
    FOREIGN KEY (`status`)
    REFERENCES `db_loja`.`tb_status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_loja`.`tb_provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_loja`.`tb_provider` (
  `id_provider` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NULL,
  `phone` INT NULL,
  `status` INT NULL,
  PRIMARY KEY (`id_provider`),
  INDEX `fk_provider_status_idx` (`status` ASC) VISIBLE,
  CONSTRAINT `fk_provider_status`
    FOREIGN KEY (`status`)
    REFERENCES `db_loja`.`tb_status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_loja`.`tb_stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_loja`.`tb_stock` (
  `amount` INT NOT NULL,
  `id_product` INT NULL,
  `status` INT NULL,
  PRIMARY KEY (`amount`),
  INDEX `fk_stack_status_idx` (`status` ASC) VISIBLE,
  CONSTRAINT `fk_stack_status`
    FOREIGN KEY (`status`)
    REFERENCES `db_loja`.`tb_status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_loja`.`tb_brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_loja`.`tb_brand` (
  `id_brand` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NULL,
  `status` INT NULL,
  PRIMARY KEY (`id_brand`),
  INDEX `fk_brand_status_idx` (`status` ASC) VISIBLE,
  CONSTRAINT `fk_brand_status`
    FOREIGN KEY (`status`)
    REFERENCES `db_loja`.`tb_status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_loja`.`tb_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_loja`.`tb_product` (
  `id_product` INT NOT NULL AUTO_INCREMENT,
  `id_provider` INT NULL,
  `id_brand` INT NULL,
  `id_type` INT NOT NULL COMMENT 'Para referenciar com o tipo de produto, coo camiseta,caneca, etc.',
  `description` VARCHAR(10000) NULL,
  `name` VARCHAR(100) NULL,
  `title` VARCHAR(100) NULL,
  `value` FLOAT(4,2) NULL,
  `value_cost` FLOAT(4,2) NULL,
  `amount` INT NULL,
  `status` INT NULL,
  PRIMARY KEY (`id_product`, `id_type`),
  INDEX `fk_product_type_idx` (`id_type` ASC) VISIBLE,
  INDEX `fk_product_provider_idx` (`id_provider` ASC) VISIBLE,
  INDEX `fk_product_stock_idx` (`amount` ASC) VISIBLE,
  INDEX `fk_product_brand_idx` (`id_brand` ASC) VISIBLE,
  INDEX `ky_product_status_idx` (`status` ASC) VISIBLE,
  CONSTRAINT `fk_product_type`
    FOREIGN KEY (`id_type`)
    REFERENCES `db_loja`.`tb_type` (`id_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_provider`
    FOREIGN KEY (`id_provider`)
    REFERENCES `db_loja`.`tb_provider` (`id_provider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_stock`
    FOREIGN KEY (`amount`)
    REFERENCES `db_loja`.`tb_stock` (`amount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_brand`
    FOREIGN KEY (`id_brand`)
    REFERENCES `db_loja`.`tb_brand` (`id_brand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ky_product_status`
    FOREIGN KEY (`status`)
    REFERENCES `db_loja`.`tb_status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_loja`.`tb_cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_loja`.`tb_cart` (
  `id_cart` INT NOT NULL,
  `id_product` INT NULL,
  `id_user` INT NULL,
  `ammount` INT NULL,
  `status` INT NULL,
  PRIMARY KEY (`id_cart`),
  INDEX `fk_cart_product_idx` (`id_product` ASC) VISIBLE,
  INDEX `fk_cart_user_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_cart_status_idx` (`status` ASC) VISIBLE,
  CONSTRAINT `fk_cart_product`
    FOREIGN KEY (`id_product`)
    REFERENCES `db_loja`.`tb_product` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `db_loja`.`tb_user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_status`
    FOREIGN KEY (`status`)
    REFERENCES `db_loja`.`tb_status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_loja`.`tb_sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_loja`.`tb_sale` (
  `id_sale` INT NOT NULL AUTO_INCREMENT,
  `id_cart` INT NULL,
  `status` INT NULL,
  PRIMARY KEY (`id_sale`),
  INDEX `fk_sale_cart_idx` (`id_cart` ASC) VISIBLE,
  CONSTRAINT `fk_sale_cart`
    FOREIGN KEY (`id_cart`)
    REFERENCES `db_loja`.`tb_cart` (`id_cart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sale_status`
    FOREIGN KEY (`status`)
    REFERENCES `db_loja`.`tb_status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_loja`.`tb_password_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_loja`.`tb_password_user` (
  `id_user` INT NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `status` INT NULL,
  PRIMARY KEY (`id_user`),
  INDEX `fk_password_user_status_idx` (`status` ASC) VISIBLE,
  CONSTRAINT `fk_password_user_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `db_loja`.`tb_user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_password_user_status`
    FOREIGN KEY (`status`)
    REFERENCES `db_loja`.`tb_status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_loja`.`tb_delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_loja`.`tb_delivery` (
  `id_delivery` INT NOT NULL AUTO_INCREMENT,
  `id_sale` INT NULL,
  `id_user` INT NULL,
  `status` INT NULL,
  PRIMARY KEY (`id_delivery`),
  INDEX `fk_delivery_sale_idx` (`id_sale` ASC) VISIBLE,
  INDEX `fk_delivery_user_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_delivery_status_idx` (`status` ASC) VISIBLE,
  CONSTRAINT `fk_delivery_sale`
    FOREIGN KEY (`id_sale`)
    REFERENCES `db_loja`.`tb_sale` (`id_sale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_delivery_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `db_loja`.`tb_user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_delivery_status`
    FOREIGN KEY (`status`)
    REFERENCES `db_loja`.`tb_status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
